from PyQt5 import QtCore, QtGui, QtWidgets
from img import img
from icons import res


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1655, 996)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frmPrincipal = QtWidgets.QFrame(self.centralwidget)
        self.frmPrincipal.setStyleSheet("background-color: rgb(248, 248, 248);")
        self.frmPrincipal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmPrincipal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmPrincipal.setObjectName("frmPrincipal")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frmPrincipal)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frmBarraLateral = QtWidgets.QFrame(self.frmPrincipal)
        self.frmBarraLateral.setMinimumSize(QtCore.QSize(350, 0))
        self.frmBarraLateral.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frmBarraLateral.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmBarraLateral.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmBarraLateral.setObjectName("frmBarraLateral")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frmBarraLateral)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frmMenu = QtWidgets.QFrame(self.frmBarraLateral)
        self.frmMenu.setMinimumSize(QtCore.QSize(0, 50))
        self.frmMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmMenu.setObjectName("frmMenu")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frmMenu)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(291, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnMenu = QtWidgets.QPushButton(self.frmMenu)
        self.btnMenu.setMinimumSize(QtCore.QSize(45, 45))
        self.btnMenu.setStyleSheet("border: none;\n"
"image: url(:/icons/menu.png);")
        self.btnMenu.setText("")
        self.btnMenu.setObjectName("btnMenu")
        self.horizontalLayout_2.addWidget(self.btnMenu)
        self.verticalLayout_2.addWidget(self.frmMenu)
        self.frmProductos = QtWidgets.QFrame(self.frmBarraLateral)
        self.frmProductos.setMinimumSize(QtCore.QSize(350, 250))
        self.frmProductos.setMaximumSize(QtCore.QSize(0, 250))
        self.frmProductos.setStyleSheet("")
        self.frmProductos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmProductos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmProductos.setObjectName("frmProductos")
        self.btnProductos = QtWidgets.QPushButton(self.frmProductos)
        self.btnProductos.setGeometry(QtCore.QRect(0, 0, 231, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnProductos.setFont(font)
        self.btnProductos.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(197, 197, 197);")
        self.btnProductos.setObjectName("btnProductos")
        self.label = QtWidgets.QLabel(self.frmProductos)
        self.label.setGeometry(QtCore.QRect(240, 0, 41, 41))
        self.label.setStyleSheet("image: url(:/icons/caja.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.frmBtnsProductos = QtWidgets.QFrame(self.frmProductos)
        self.frmBtnsProductos.setGeometry(QtCore.QRect(0, 50, 351, 191))
        self.frmBtnsProductos.setStyleSheet("QPushButton{\n"
"    background-color: rgb(129, 129, 129);\n"
"    border-radius: 10px;\n"
"    color: rgb(255,255,255);\n"
"    font: 10pt;\n"
"    text-align: left;\n"
"    padding-left: 10px;\n"
"}\n"
"QLabel{\n"
"    image: url(:/icons/proximo.png);\n"
"}")
        self.frmBtnsProductos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmBtnsProductos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmBtnsProductos.setObjectName("frmBtnsProductos")
        self.pushButton = QtWidgets.QPushButton(self.frmBtnsProductos)
        self.pushButton.setGeometry(QtCore.QRect(40, 0, 161, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frmBtnsProductos)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 40, 161, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frmBtnsProductos)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 80, 161, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frmBtnsProductos)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 120, 161, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frmBtnsProductos)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 160, 161, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_4 = QtWidgets.QLabel(self.frmBtnsProductos)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 31, 31))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frmBtnsProductos)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 31, 31))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frmBtnsProductos)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 31, 31))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frmBtnsProductos)
        self.label_7.setGeometry(QtCore.QRect(10, 120, 31, 31))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frmBtnsProductos)
        self.label_8.setGeometry(QtCore.QRect(10, 160, 31, 31))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.frmProductos)
        spacerItem1 = QtWidgets.QSpacerItem(20, 41, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.frmEmpleados = QtWidgets.QFrame(self.frmBarraLateral)
        self.frmEmpleados.setMinimumSize(QtCore.QSize(350, 250))
        self.frmEmpleados.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frmEmpleados.setStyleSheet("")
        self.frmEmpleados.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmEmpleados.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmEmpleados.setObjectName("frmEmpleados")
        self.btnEmpleados = QtWidgets.QPushButton(self.frmEmpleados)
        self.btnEmpleados.setGeometry(QtCore.QRect(0, 0, 231, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnEmpleados.setFont(font)
        self.btnEmpleados.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(197, 197, 197);")
        self.btnEmpleados.setObjectName("btnEmpleados")
        self.label_2 = QtWidgets.QLabel(self.frmEmpleados)
        self.label_2.setGeometry(QtCore.QRect(240, 0, 41, 41))
        self.label_2.setStyleSheet("image: url(:/icons/empleado.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.frmBtnsEmpleados = QtWidgets.QFrame(self.frmEmpleados)
        self.frmBtnsEmpleados.setGeometry(QtCore.QRect(0, 50, 351, 191))
        self.frmBtnsEmpleados.setStyleSheet("QPushButton{\n"
"    background-color: rgb(129, 129, 129);\n"
"    border-radius: 10px;\n"
"    color: rgb(255,255,255);\n"
"    font: 10pt;\n"
"    text-align: left;\n"
"    padding-left: 10px;\n"
"}\n"
"QLabel{\n"
"    image: url(:/icons/proximo.png);\n"
"}")
        self.frmBtnsEmpleados.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmBtnsEmpleados.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmBtnsEmpleados.setObjectName("frmBtnsEmpleados")
        self.pushButton_6 = QtWidgets.QPushButton(self.frmBtnsEmpleados)
        self.pushButton_6.setGeometry(QtCore.QRect(40, 0, 161, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frmBtnsEmpleados)
        self.pushButton_7.setGeometry(QtCore.QRect(40, 50, 161, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frmBtnsEmpleados)
        self.pushButton_8.setGeometry(QtCore.QRect(40, 100, 161, 28))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.frmBtnsEmpleados)
        self.pushButton_9.setGeometry(QtCore.QRect(40, 150, 161, 28))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_9 = QtWidgets.QLabel(self.frmBtnsEmpleados)
        self.label_9.setGeometry(QtCore.QRect(10, 0, 31, 31))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frmBtnsEmpleados)
        self.label_10.setGeometry(QtCore.QRect(10, 50, 31, 31))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frmBtnsEmpleados)
        self.label_11.setGeometry(QtCore.QRect(10, 100, 31, 31))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frmBtnsEmpleados)
        self.label_12.setGeometry(QtCore.QRect(10, 150, 31, 31))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.frmEmpleados)
        spacerItem2 = QtWidgets.QSpacerItem(20, 41, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.frmVentas = QtWidgets.QFrame(self.frmBarraLateral)
        self.frmVentas.setMinimumSize(QtCore.QSize(350, 250))
        self.frmVentas.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frmVentas.setStyleSheet("")
        self.frmVentas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmVentas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmVentas.setObjectName("frmVentas")
        self.btnVentas = QtWidgets.QPushButton(self.frmVentas)
        self.btnVentas.setGeometry(QtCore.QRect(0, 0, 231, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnVentas.setFont(font)
        self.btnVentas.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(197, 197, 197);")
        self.btnVentas.setObjectName("btnVentas")
        self.label_3 = QtWidgets.QLabel(self.frmVentas)
        self.label_3.setGeometry(QtCore.QRect(240, 0, 41, 41))
        self.label_3.setStyleSheet("image: url(:/icons/ventas.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.frmBtnsVentas = QtWidgets.QFrame(self.frmVentas)
        self.frmBtnsVentas.setGeometry(QtCore.QRect(0, 50, 351, 191))
        self.frmBtnsVentas.setStyleSheet("QPushButton{\n"
"    background-color: rgb(129, 129, 129);\n"
"    border-radius: 10px;\n"
"    color: rgb(255,255,255);\n"
"    font: 10pt;\n"
"    text-align: left;\n"
"    padding-left: 10px;\n"
"}\n"
"QLabel{\n"
"    image: url(:/icons/proximo.png);\n"
"}")
        self.frmBtnsVentas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmBtnsVentas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmBtnsVentas.setObjectName("frmBtnsVentas")
        self.pushButton_10 = QtWidgets.QPushButton(self.frmBtnsVentas)
        self.pushButton_10.setGeometry(QtCore.QRect(40, 0, 191, 28))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.frmBtnsVentas)
        self.pushButton_11.setGeometry(QtCore.QRect(40, 70, 191, 28))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.frmBtnsVentas)
        self.pushButton_12.setGeometry(QtCore.QRect(40, 140, 191, 28))
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_13 = QtWidgets.QLabel(self.frmBtnsVentas)
        self.label_13.setGeometry(QtCore.QRect(10, 0, 31, 31))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frmBtnsVentas)
        self.label_14.setGeometry(QtCore.QRect(10, 70, 31, 31))
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frmBtnsVentas)
        self.label_15.setGeometry(QtCore.QRect(10, 140, 31, 31))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.frmVentas)
        spacerItem3 = QtWidgets.QSpacerItem(20, 41, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.frmSalir = QtWidgets.QFrame(self.frmBarraLateral)
        self.frmSalir.setMinimumSize(QtCore.QSize(350, 60))
        self.frmSalir.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frmSalir.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmSalir.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmSalir.setObjectName("frmSalir")
        self.label_16 = QtWidgets.QLabel(self.frmSalir)
        self.label_16.setGeometry(QtCore.QRect(0, 20, 131, 21))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frmSalir)
        self.label_17.setGeometry(QtCore.QRect(120, 17, 41, 31))
        self.label_17.setStyleSheet("image: url(:/icons/cerrar-sesion.png);")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.frmSalir)
        self.horizontalLayout.addWidget(self.frmBarraLateral)
        self.frmContenido = QtWidgets.QFrame(self.frmPrincipal)
        self.frmContenido.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmContenido.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmContenido.setObjectName("frmContenido")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frmContenido)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frmContenido)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pagePrincipal = QtWidgets.QWidget()
        self.pagePrincipal.setStyleSheet("QFrame#fondo{\n"
"    border-image: url(:/img/aguacate.jpg);\n"
"}\n"
"QFrame#sombra{\n"
"    background-color: rgba(0,0,0,70);\n"
"}")
        self.pagePrincipal.setObjectName("pagePrincipal")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pagePrincipal)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.fondo = QtWidgets.QFrame(self.pagePrincipal)
        self.fondo.setStyleSheet("")
        self.fondo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fondo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fondo.setObjectName("fondo")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.fondo)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.sombra = QtWidgets.QFrame(self.fondo)
        self.sombra.setStyleSheet("")
        self.sombra.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sombra.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sombra.setObjectName("sombra")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.sombra)
        self.verticalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_32.setSpacing(0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.frame = QtWidgets.QFrame(self.sombra)
        self.frame.setMinimumSize(QtCore.QSize(0, 100))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.label_18 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"color: rgb(255,255,255);")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_3.addWidget(self.label_18)
        spacerItem5 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_32.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.sombra)
        self.frame_2.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(442, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.btnNuevaVenta = QtWidgets.QPushButton(self.frame_2)
        self.btnNuevaVenta.setMinimumSize(QtCore.QSize(250, 65))
        self.btnNuevaVenta.setMaximumSize(QtCore.QSize(0, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btnNuevaVenta.setFont(font)
        self.btnNuevaVenta.setStyleSheet("color: rgb(255,255,255);\n"
"background-color: rgb(    85, 99, 171);\n"
"border-radius:15px;")
        self.btnNuevaVenta.setObjectName("btnNuevaVenta")
        self.horizontalLayout_4.addWidget(self.btnNuevaVenta)
        spacerItem7 = QtWidgets.QSpacerItem(441, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout_32.addWidget(self.frame_2)
        self.verticalLayout_18.addWidget(self.sombra)
        self.verticalLayout_4.addWidget(self.fondo)
        self.stackedWidget.addWidget(self.pagePrincipal)
        self.pageVenta = QtWidgets.QWidget()
        self.pageVenta.setStyleSheet("QFrame#fondo_2{\n"
"    \n"
"    border-image: url(:/img/aguacate.jpg);\n"
"}\n"
"QFrame#sombra_2{\n"
"    background-color: rgba(0,0,0,70);\n"
"}")
        self.pageVenta.setObjectName("pageVenta")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pageVenta)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.fondo_2 = QtWidgets.QFrame(self.pageVenta)
        self.fondo_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fondo_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fondo_2.setObjectName("fondo_2")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.fondo_2)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.sombra_2 = QtWidgets.QFrame(self.fondo_2)
        self.sombra_2.setStyleSheet("")
        self.sombra_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sombra_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sombra_2.setObjectName("sombra_2")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.sombra_2)
        self.verticalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_33.setSpacing(0)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.frame_3 = QtWidgets.QFrame(self.sombra_2)
        self.frame_3.setStyleSheet("background-color: rgba(245, 245, 245);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_34.setSpacing(0)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.frmSuperior = QtWidgets.QFrame(self.frame_3)
        self.frmSuperior.setMinimumSize(QtCore.QSize(0, 0))
        self.frmSuperior.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frmSuperior.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.frmSuperior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmSuperior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmSuperior.setObjectName("frmSuperior")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frmSuperior)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_19 = QtWidgets.QLabel(self.frmSuperior)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_5.addWidget(self.label_19)
        spacerItem8 = QtWidgets.QSpacerItem(372, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.label_20 = QtWidgets.QLabel(self.frmSuperior)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_5.addWidget(self.label_20)
        spacerItem9 = QtWidgets.QSpacerItem(371, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.label_21 = QtWidgets.QLabel(self.frmSuperior)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_5.addWidget(self.label_21)
        self.verticalLayout_34.addWidget(self.frmSuperior)
        self.frmDatos = QtWidgets.QFrame(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.frmDatos.setFont(font)
        self.frmDatos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmDatos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmDatos.setObjectName("frmDatos")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frmDatos)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem10 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.frmDatosIzq = QtWidgets.QFrame(self.frmDatos)
        self.frmDatosIzq.setMinimumSize(QtCore.QSize(700, 0))
        self.frmDatosIzq.setMaximumSize(QtCore.QSize(16777215, 500))
        self.frmDatosIzq.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmDatosIzq.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmDatosIzq.setObjectName("frmDatosIzq")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frmDatosIzq)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_9 = QtWidgets.QFrame(self.frmDatosIzq)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_9.setMaximumSize(QtCore.QSize(260, 500))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        spacerItem11 = QtWidgets.QSpacerItem(20, 43, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_37.addItem(spacerItem11)
        self.label_22 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_37.addWidget(self.label_22)
        spacerItem12 = QtWidgets.QSpacerItem(20, 42, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_37.addItem(spacerItem12)
        self.label_23 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_37.addWidget(self.label_23)
        spacerItem13 = QtWidgets.QSpacerItem(20, 43, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_37.addItem(spacerItem13)
        self.label_24 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_37.addWidget(self.label_24)
        spacerItem14 = QtWidgets.QSpacerItem(20, 42, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_37.addItem(spacerItem14)
        self.label_25 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_37.addWidget(self.label_25)
        spacerItem15 = QtWidgets.QSpacerItem(20, 43, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_37.addItem(spacerItem15)
        self.horizontalLayout_7.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frmDatosIzq)
        self.frame_10.setMaximumSize(QtCore.QSize(300, 500))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        spacerItem16 = QtWidgets.QSpacerItem(20, 34, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_36.addItem(spacerItem16)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_36.addWidget(self.lineEdit)
        spacerItem17 = QtWidgets.QSpacerItem(20, 33, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_36.addItem(spacerItem17)
        self.spinBox = QtWidgets.QSpinBox(self.frame_10)
        self.spinBox.setMinimumSize(QtCore.QSize(0, 40))
        self.spinBox.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox.setFont(font)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_36.addWidget(self.spinBox)
        spacerItem18 = QtWidgets.QSpacerItem(20, 34, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_36.addItem(spacerItem18)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_36.addWidget(self.lineEdit_3)
        spacerItem19 = QtWidgets.QSpacerItem(20, 33, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_36.addItem(spacerItem19)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_36.addWidget(self.lineEdit_4)
        spacerItem20 = QtWidgets.QSpacerItem(20, 34, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_36.addItem(spacerItem20)
        self.horizontalLayout_7.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frmDatosIzq)
        self.frame_11.setMaximumSize(QtCore.QSize(150, 500))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        spacerItem21 = QtWidgets.QSpacerItem(20, 87, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_35.addItem(spacerItem21)
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_13.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_13.setMaximumSize(QtCore.QSize(125, 50))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("background-color: rgb(70, 60, 190);\n"
"border-radius: 15px;\n"
"color: rgb(255,255,255);")
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_35.addWidget(self.pushButton_13)
        spacerItem22 = QtWidgets.QSpacerItem(20, 88, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_35.addItem(spacerItem22)
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_14.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_14.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("background-color: rgb(144, 33, 163);\n"
"color: rgb(255,255,255);\n"
"border-radius:15px;")
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_35.addWidget(self.pushButton_14)
        spacerItem23 = QtWidgets.QSpacerItem(20, 87, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_35.addItem(spacerItem23)
        self.horizontalLayout_7.addWidget(self.frame_11)
        self.horizontalLayout_6.addWidget(self.frmDatosIzq)
        spacerItem24 = QtWidgets.QSpacerItem(4, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem24)
        self.frmDatosDer = QtWidgets.QFrame(self.frmDatos)
        self.frmDatosDer.setMinimumSize(QtCore.QSize(500, 0))
        self.frmDatosDer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmDatosDer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmDatosDer.setObjectName("frmDatosDer")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frmDatosDer)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_12 = QtWidgets.QFrame(self.frmDatosDer)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 500))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.frame_4 = QtWidgets.QFrame(self.frame_12)
        self.frame_4.setGeometry(QtCore.QRect(10, 10, 191, 220))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_38.addItem(spacerItem25)
        self.label_26 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_38.addWidget(self.label_26)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_38.addItem(spacerItem26)
        self.label_27 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_38.addWidget(self.label_27)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_38.addItem(spacerItem27)
        self.frame_6 = QtWidgets.QFrame(self.frame_12)
        self.frame_6.setGeometry(QtCore.QRect(10, 240, 191, 151))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.label_28 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_39.addWidget(self.label_28)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_39.addItem(spacerItem28)
        self.horizontalLayout_8.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frmDatosDer)
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 500))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.frame_5 = QtWidgets.QFrame(self.frame_13)
        self.frame_5.setGeometry(QtCore.QRect(10, 10, 261, 228))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        spacerItem29 = QtWidgets.QSpacerItem(20, 34, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_40.addItem(spacerItem29)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_40.addWidget(self.lineEdit_6)
        spacerItem30 = QtWidgets.QSpacerItem(20, 32, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_40.addItem(spacerItem30)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_40.addWidget(self.lineEdit_5)
        spacerItem31 = QtWidgets.QSpacerItem(20, 31, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_40.addItem(spacerItem31)
        self.frame_7 = QtWidgets.QFrame(self.frame_13)
        self.frame_7.setGeometry(QtCore.QRect(10, 250, 260, 141))
        self.frame_7.setMinimumSize(QtCore.QSize(260, 0))
        self.frame_7.setMaximumSize(QtCore.QSize(240, 141))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.textEdit = QtWidgets.QTextEdit(self.frame_7)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_41.addWidget(self.textEdit)
        spacerItem32 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_41.addItem(spacerItem32)
        self.horizontalLayout_8.addWidget(self.frame_13)
        self.horizontalLayout_6.addWidget(self.frmDatosDer)
        spacerItem33 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem33)
        self.verticalLayout_34.addWidget(self.frmDatos)
        self.verticalLayout_33.addWidget(self.frame_3)
        self.frmTabla = QtWidgets.QFrame(self.sombra_2)
        self.frmTabla.setMinimumSize(QtCore.QSize(0, 500))
        self.frmTabla.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.frmTabla.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmTabla.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmTabla.setObjectName("frmTabla")
        self.verticalLayout_33.addWidget(self.frmTabla)
        self.verticalLayout_19.addWidget(self.sombra_2)
        self.verticalLayout_5.addWidget(self.fondo_2)
        self.stackedWidget.addWidget(self.pageVenta)
        self.pageProducto_registrar = QtWidgets.QWidget()
        self.pageProducto_registrar.setStyleSheet("QFrame#fondo_3{\n"
"    border-image: url(:/img/aguacate.jpg);\n"
"}\n"
"QFrame#sombra_3{\n"
"    background-color: rgba(0,0,0,70);\n"
"}")
        self.pageProducto_registrar.setObjectName("pageProducto_registrar")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.pageProducto_registrar)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fondo_3 = QtWidgets.QFrame(self.pageProducto_registrar)
        self.fondo_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fondo_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fondo_3.setObjectName("fondo_3")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.fondo_3)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.sombra_3 = QtWidgets.QFrame(self.fondo_3)
        self.sombra_3.setStyleSheet("")
        self.sombra_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sombra_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sombra_3.setObjectName("sombra_3")
        self.verticalLayout_20.addWidget(self.sombra_3)
        self.verticalLayout_6.addWidget(self.fondo_3)
        self.stackedWidget.addWidget(self.pageProducto_registrar)
        self.pageProducto_aniadir = QtWidgets.QWidget()
        self.pageProducto_aniadir.setStyleSheet("QFrame#fondo_4{\n"
"    border-image: url(:/img/aguacate.jpg);\n"
"}\n"
"QFrame#sombra_4{\n"
"    background-color: rgba(0,0,0,70);\n"
"}")
        self.pageProducto_aniadir.setObjectName("pageProducto_aniadir")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pageProducto_aniadir)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.fondo_4 = QtWidgets.QFrame(self.pageProducto_aniadir)
        self.fondo_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fondo_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fondo_4.setObjectName("fondo_4")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.fondo_4)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.sombra_4 = QtWidgets.QFrame(self.fondo_4)
        self.sombra_4.setStyleSheet("")
        self.sombra_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sombra_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sombra_4.setObjectName("sombra_4")
        self.verticalLayout_21.addWidget(self.sombra_4)
        self.verticalLayout_7.addWidget(self.fondo_4)
        self.stackedWidget.addWidget(self.pageProducto_aniadir)
        self.pageProducto_consultar = QtWidgets.QWidget()
        self.pageProducto_consultar.setStyleSheet("QFrame#fondo_5{\n"
"    border-image: url(:/img/aguacate.jpg);\n"
"}\n"
"QFrame#sombra_5{\n"
"    background-color: rgba(0,0,0,70);\n"
"}")
        self.pageProducto_consultar.setObjectName("pageProducto_consultar")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.pageProducto_consultar)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.fondo_5 = QtWidgets.QFrame(self.pageProducto_consultar)
        self.fondo_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fondo_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fondo_5.setObjectName("fondo_5")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.fondo_5)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.sombra_5 = QtWidgets.QFrame(self.fondo_5)
        self.sombra_5.setStyleSheet("")
        self.sombra_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sombra_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sombra_5.setObjectName("sombra_5")
        self.verticalLayout_22.addWidget(self.sombra_5)
        self.verticalLayout_8.addWidget(self.fondo_5)
        self.stackedWidget.addWidget(self.pageProducto_consultar)
        self.pageProducto_modificar = QtWidgets.QWidget()
        self.pageProducto_modificar.setStyleSheet("QFrame#fondo_6{\n"
"    border-image: url(:/img/aguacate.jpg);\n"
"}\n"
"QFrame#sombra_6{\n"
"    background-color: rgba(0,0,0,70);\n"
"}")
        self.pageProducto_modificar.setObjectName("pageProducto_modificar")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.pageProducto_modificar)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.fondo_6 = QtWidgets.QFrame(self.pageProducto_modificar)
        self.fondo_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fondo_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fondo_6.setObjectName("fondo_6")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.fondo_6)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.sombra_6 = QtWidgets.QFrame(self.fondo_6)
        self.sombra_6.setStyleSheet("")
        self.sombra_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sombra_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sombra_6.setObjectName("sombra_6")
        self.verticalLayout_23.addWidget(self.sombra_6)
        self.verticalLayout_9.addWidget(self.fondo_6)
        self.stackedWidget.addWidget(self.pageProducto_modificar)
        self.pageProducto_eliminar = QtWidgets.QWidget()
        self.pageProducto_eliminar.setStyleSheet("QFrame#fondo_7{\n"
"    border-image: url(:/img/aguacate.jpg);\n"
"}\n"
"QFrame#sombra_7{\n"
"    background-color: rgba(0,0,0,70);\n"
"}")
        self.pageProducto_eliminar.setObjectName("pageProducto_eliminar")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.pageProducto_eliminar)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.fondo_7 = QtWidgets.QFrame(self.pageProducto_eliminar)
        self.fondo_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fondo_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fondo_7.setObjectName("fondo_7")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.fondo_7)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.sombra_7 = QtWidgets.QFrame(self.fondo_7)
        self.sombra_7.setStyleSheet("")
        self.sombra_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sombra_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sombra_7.setObjectName("sombra_7")
        self.verticalLayout_24.addWidget(self.sombra_7)
        self.verticalLayout_10.addWidget(self.fondo_7)
        self.stackedWidget.addWidget(self.pageProducto_eliminar)
        self.pageEmpleado_registrar = QtWidgets.QWidget()
        self.pageEmpleado_registrar.setStyleSheet("QFrame#fondo_8{\n"
"    border-image: url(:/img/aguacate.jpg);\n"
"}\n"
"QFrame#sombra_8{\n"
"    background-color: rgba(0,0,0,70);\n"
"}")
        self.pageEmpleado_registrar.setObjectName("pageEmpleado_registrar")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.pageEmpleado_registrar)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.fondo_8 = QtWidgets.QFrame(self.pageEmpleado_registrar)
        self.fondo_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fondo_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fondo_8.setObjectName("fondo_8")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.fondo_8)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.sombra_8 = QtWidgets.QFrame(self.fondo_8)
        self.sombra_8.setStyleSheet("")
        self.sombra_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sombra_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sombra_8.setObjectName("sombra_8")
        self.verticalLayout_25.addWidget(self.sombra_8)
        self.verticalLayout_11.addWidget(self.fondo_8)
        self.stackedWidget.addWidget(self.pageEmpleado_registrar)
        self.pageEmpleado_consultar = QtWidgets.QWidget()
        self.pageEmpleado_consultar.setStyleSheet("QFrame#fondo_9{\n"
"    border-image: url(:/img/aguacate.jpg);\n"
"}\n"
"QFrame#sombra_9{\n"
"    background-color: rgba(0,0,0,70);\n"
"}")
        self.pageEmpleado_consultar.setObjectName("pageEmpleado_consultar")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.pageEmpleado_consultar)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.fondo_9 = QtWidgets.QFrame(self.pageEmpleado_consultar)
        self.fondo_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fondo_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fondo_9.setObjectName("fondo_9")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.fondo_9)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.sombra_9 = QtWidgets.QFrame(self.fondo_9)
        self.sombra_9.setStyleSheet("")
        self.sombra_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sombra_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sombra_9.setObjectName("sombra_9")
        self.verticalLayout_26.addWidget(self.sombra_9)
        self.verticalLayout_12.addWidget(self.fondo_9)
        self.stackedWidget.addWidget(self.pageEmpleado_consultar)
        self.pageEmpleado_modificar = QtWidgets.QWidget()
        self.pageEmpleado_modificar.setStyleSheet("QFrame#fondo_10{\n"
"    border-image: url(:/img/aguacate.jpg);\n"
"}\n"
"QFrame#sombra_10{\n"
"    background-color: rgba(0,0,0,70);\n"
"}")
        self.pageEmpleado_modificar.setObjectName("pageEmpleado_modificar")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.pageEmpleado_modificar)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.fondo_10 = QtWidgets.QFrame(self.pageEmpleado_modificar)
        self.fondo_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fondo_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fondo_10.setObjectName("fondo_10")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.fondo_10)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setSpacing(0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.sombra_10 = QtWidgets.QFrame(self.fondo_10)
        self.sombra_10.setStyleSheet("")
        self.sombra_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sombra_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sombra_10.setObjectName("sombra_10")
        self.verticalLayout_27.addWidget(self.sombra_10)
        self.verticalLayout_13.addWidget(self.fondo_10)
        self.stackedWidget.addWidget(self.pageEmpleado_modificar)
        self.pageEmpleado_eliminar = QtWidgets.QWidget()
        self.pageEmpleado_eliminar.setStyleSheet("QFrame#fondo_11{\n"
"    border-image: url(:/img/aguacate.jpg);\n"
"}\n"
"QFrame#sombra_11{\n"
"    background-color: rgba(0,0,0,70);\n"
"}")
        self.pageEmpleado_eliminar.setObjectName("pageEmpleado_eliminar")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.pageEmpleado_eliminar)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.fondo_11 = QtWidgets.QFrame(self.pageEmpleado_eliminar)
        self.fondo_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fondo_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fondo_11.setObjectName("fondo_11")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.fondo_11)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setSpacing(0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.sombra_11 = QtWidgets.QFrame(self.fondo_11)
        self.sombra_11.setStyleSheet("")
        self.sombra_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sombra_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sombra_11.setObjectName("sombra_11")
        self.verticalLayout_28.addWidget(self.sombra_11)
        self.verticalLayout_14.addWidget(self.fondo_11)
        self.stackedWidget.addWidget(self.pageEmpleado_eliminar)
        self.pageVentas_consultaruna = QtWidgets.QWidget()
        self.pageVentas_consultaruna.setStyleSheet("QFrame#fondo_12{\n"
"    border-image: url(:/img/aguacate.jpg);\n"
"}\n"
"QFrame#sombra_12{\n"
"    background-color: rgba(0,0,0,70);\n"
"}")
        self.pageVentas_consultaruna.setObjectName("pageVentas_consultaruna")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.pageVentas_consultaruna)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.fondo_12 = QtWidgets.QFrame(self.pageVentas_consultaruna)
        self.fondo_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fondo_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fondo_12.setObjectName("fondo_12")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.fondo_12)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setSpacing(0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.sombra_12 = QtWidgets.QFrame(self.fondo_12)
        self.sombra_12.setStyleSheet("")
        self.sombra_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sombra_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sombra_12.setObjectName("sombra_12")
        self.verticalLayout_29.addWidget(self.sombra_12)
        self.verticalLayout_15.addWidget(self.fondo_12)
        self.stackedWidget.addWidget(self.pageVentas_consultaruna)
        self.pageVentas_consultarpor = QtWidgets.QWidget()
        self.pageVentas_consultarpor.setStyleSheet("QFrame#fondo_13{\n"
"    border-image: url(:/img/aguacate.jpg);\n"
"}\n"
"QFrame#sombra_13{\n"
"    background-color: rgba(0,0,0,70);\n"
"}")
        self.pageVentas_consultarpor.setObjectName("pageVentas_consultarpor")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.pageVentas_consultarpor)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.fondo_13 = QtWidgets.QFrame(self.pageVentas_consultarpor)
        self.fondo_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fondo_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fondo_13.setObjectName("fondo_13")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.fondo_13)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setSpacing(0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.sombra_13 = QtWidgets.QFrame(self.fondo_13)
        self.sombra_13.setStyleSheet("")
        self.sombra_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sombra_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sombra_13.setObjectName("sombra_13")
        self.verticalLayout_30.addWidget(self.sombra_13)
        self.verticalLayout_16.addWidget(self.fondo_13)
        self.stackedWidget.addWidget(self.pageVentas_consultarpor)
        self.pageVentas_corte = QtWidgets.QWidget()
        self.pageVentas_corte.setStyleSheet("QFrame#fondo_14{\n"
"    border-image: url(:/img/aguacate.jpg);\n"
"}\n"
"QFrame#sombra_14{\n"
"    background-color: rgba(0,0,0,70);\n"
"}")
        self.pageVentas_corte.setObjectName("pageVentas_corte")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.pageVentas_corte)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.fondo_14 = QtWidgets.QFrame(self.pageVentas_corte)
        self.fondo_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fondo_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fondo_14.setObjectName("fondo_14")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.fondo_14)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setSpacing(0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.sombra_14 = QtWidgets.QFrame(self.fondo_14)
        self.sombra_14.setStyleSheet("")
        self.sombra_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sombra_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sombra_14.setObjectName("sombra_14")
        self.verticalLayout_31.addWidget(self.sombra_14)
        self.verticalLayout_17.addWidget(self.fondo_14)
        self.stackedWidget.addWidget(self.pageVentas_corte)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.frmContenido)
        self.verticalLayout.addWidget(self.frmPrincipal)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnProductos.setText(_translate("MainWindow", "Productos"))
        self.pushButton.setText(_translate("MainWindow", "Registrar nuevo"))
        self.pushButton_2.setText(_translate("MainWindow", "Añadir unidades"))
        self.pushButton_3.setText(_translate("MainWindow", "Consultar producto"))
        self.pushButton_4.setText(_translate("MainWindow", "Modificar producto"))
        self.pushButton_5.setText(_translate("MainWindow", "Eliminar producto"))
        self.btnEmpleados.setText(_translate("MainWindow", "Empleados"))
        self.pushButton_6.setText(_translate("MainWindow", "Registrar"))
        self.pushButton_7.setText(_translate("MainWindow", "Consultar"))
        self.pushButton_8.setText(_translate("MainWindow", "Modificar"))
        self.pushButton_9.setText(_translate("MainWindow", "Eliminar"))
        self.btnVentas.setText(_translate("MainWindow", "Ventas"))
        self.pushButton_10.setText(_translate("MainWindow", "Consultar una venta"))
        self.pushButton_11.setText(_translate("MainWindow", "Consultar venta por"))
        self.pushButton_12.setText(_translate("MainWindow", "Corte de caja"))
        self.label_16.setText(_translate("MainWindow", "Cerrar sesión"))
        self.label_18.setText(_translate("MainWindow", "Agroquímicos \"Nombre del local\""))
        self.btnNuevaVenta.setText(_translate("MainWindow", "Nueva Venta"))
        self.label_19.setText(_translate("MainWindow", "Folio: 1"))
        self.label_20.setText(_translate("MainWindow", "Nueva Venta"))
        self.label_21.setText(_translate("MainWindow", "17/06/2022"))
        self.label_22.setText(_translate("MainWindow", "Nombre del producto:"))
        self.label_23.setText(_translate("MainWindow", "Cantidad:"))
        self.label_24.setText(_translate("MainWindow", "Marca: "))
        self.label_25.setText(_translate("MainWindow", "Precio del producto: "))
        self.pushButton_13.setText(_translate("MainWindow", "Buscar"))
        self.pushButton_14.setText(_translate("MainWindow", "Agregar"))
        self.label_26.setText(_translate("MainWindow", "Categoría: "))
        self.label_27.setText(_translate("MainWindow", "Contenido Neto: "))
        self.label_28.setText(_translate("MainWindow", "Compuesto: "))
